name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or use your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Unit Testing
        run: npm test
        
      - name: Deploying Staging Server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@51.20.141.130'
          privatekey: ${{secrets.EC2_ACCESS_KEY}}
          command: |
            export NVM_DIR=/home/ubuntu/.nvm
            source /home/ubuntu/.nvm/nvm.sh
            cd /home/ubuntu/dev_ass_2/devop_testapp/
            git pull origin main
            npm run dev


            
